### ISSUE TITLE
Investigar cambio de CSS

### ISSUE THREAD

**Issue by isolis2000** [Coheteria-TECSpace/coheteria-tecspace.github.io#1]
Cambio de CSS para el template de Jekyll (buscar en assets/css/style/css)

**Comment by lross2k** [comment]
La [documentación](https://chirpy.cotes.page/posts/getting-started/#customing-stylesheet) describe brevemente cómo empezar a modificar el archivo `.scss` cualquier modificación al final del archivo tomará predominancia sobre los valores originales, documentar en esta discusión los cambios

Paleta de colores TECSpace
> (al momento de escribir este comentario)
- Azul #174287
- Gris #DADAD9
- Blanco #FFFFFF

**Comment by lross2k** [comment]
Usar font [Poppins](https://fonts.google.com/specimen/Poppins), debería ser igual que modificar la font de todo objeto en el CSS.

**Comment by lross2k** [comment]
@isolis2000 realizó el cambio exitosamente en https://github.com/Coheteria-TECSpace/coheteria-tecspace.github.io/pull/13, se hizo merge en a73256f
