### ISSUE TITLE
Cambiar el icono de la página web 

### ISSUE THREAD

**Issue by isolis2000** [Coheteria-TECSpace/coheteria-tecspace.github.io#2]
Investigar favicon chirpy Jekyll template

**Comment by lross2k** [comment]
Más info puede ser encontrada [acá](https://chirpy.cotes.page/posts/customize-the-favicon/)

El ícono a usar pueden encontrarlo [acá](https://drive.google.com/file/d/1PNbPsUSneIAXsq_Jox3lfiRgwmScn1gN/view?usp=sharing)

Contribuir con un pull request o bien pedirme permisos en el repostorio

**Comment by lross2k** [comment]
Cambio ya fue realizado en edf13c672f6333bfb656dd4ff18733e7d3d04694, se cierra el issue
