### ISSUE TITLE
Cambiar nombre de página web

### ISSUE THREAD

**Issue by isolis2000** [Coheteria-TECSpace/coheteria-tecspace.github.io#3]

**Comment by lross2k** [comment]
Escencialmente sólo debe cambiarse una línea de texto, incluso voy a incluir el enlace directo a continuación

https://github.com/Coheteria-TECSpace/coheteria-tecspace.github.io/blob/c20ea4976e1f6e450a969e638c93312a4c7e07ae/_config.yml#L25

Pero ya que andan en el archivo de configuraciones, pueden cambiar otras cosas y proponer mejoras en esta discusión

**Comment by ramirorayo** [comment]
title: TecSpace   #the main title

**Comment by lross2k** [comment]
> title: TecSpace #the main title

Con eso basta, pero hay que hacer el cambio en el código y envía un pull request para aceptar el cambio

**Comment by lross2k** [comment]
Cambio realizado en a4b7cca
