### ISSUE TITLE
Crear página de inicio en HTML 

### ISSUE THREAD

**Issue by isolis2000** [Coheteria-TECSpace/coheteria-tecspace.github.io#4]
Investigar colocar archivo en el repositorio base /home.html

**Comment by lross2k** [comment]
En el folder principal del repositorio se crea un archivo `NOMBRE.html` este con una syntaxis similar a la siguiente
```html
---
title: NOMBRE
layout: LAYOUT
---
Texto visible en la página coheteria-tecspace.github.io/NOMBRE
```` 

LAYOUT depende del tipo de página que se trate, podemos probar con `layout: home` para empezar, si no se ve bien, podemos probar con `layout: post`

**Comment by lross2k** [comment]
Issue finalizado puesto que el template tiene un uso distinto para el Home, como se descubrió en 1e180d8, se procede a trabajar en #5
